### ISSUE TITLE
Disable or tail console.log under task

### ISSUE THREAD

**Issue by amacierzynski** [cenk1cenk2/listr2#433] opened 2021-06-16 12:21 UTC
Hi!

I am trying to add listr2 to an already existing project with some async tasks-based architecture.
Previously we were using simple console.log for logging.

After adding listr2 I can see that for each log which we are sending, there is and duplication of the task status above.
```
⠙ Run
⠹ Run
14:14:38,207 Something added somewhere
14:14:38,280 Something else added somewhere else
⠸ Run
⠼ Run
...
```

Is there any option to keep one line for `Run` and tail console.log below to be displayed in a max of 5 latest entries?

**Comment by cenk1cenk2** [comment] 2021-06-16 12:26
hello,

https://github.com/cenk1cenk2/listr2/issues/296

i track this issue on this one. but it will still take a bit of time to reach the main stream even though it is half implemented in there are numerous problems with the current tests.

**Comment by cenk1cenk2** [comment] 2021-07-22 18:41
I will be closing this issue in favor of #296 . Feel free to reopen it any time. But the problem is acknowledged.

**Closed by cenk1cenk2** 2021-07-22 18:41 UTC
