### ISSUE TITLE
Still getting duplicated text with beta version

### ISSUE THREAD

**Issue by PalmMinecraft** [cenk1cenk2/listr2#501] opened 2021-09-08 07:49 UTC
Hello,

So I've been using listr2 for 3 days now and I noticed that it has duplicated lines.
Searched in issues and found that it was fixed in the beta version, I installed the beta version and it is still happening

Version 4.0.0-beta.3 as seen here:
![image](https://user-images.githubusercontent.com/67689562/132468453-18823ab7-9421-4f47-8e51-cb36ec4584ed.png)

**Comment by Palm2570Playz** [comment] 2021-09-10 04:35
Sorry for closing and reopening, just realized the issue wasn't the timing but this always happen when I have subtasks inside another subtask instead

**Comment by cenk1cenk2** [comment] 2021-09-12 12:20
Hello @Palm2570Playz ,

The beta version is currently too much out of date, so I do not even know what could be the problem.

But my educated guess as always for this duplicated stuff is something is trying to write to stdout. As I always discuss in other issues if I can swap the library of the terminal renderer, this should be fixed. But the problem is beta version was not a hundred percent working.

**Closed** 2021-11-02 17:44 UTC
