### ISSUE TITLE
Many tasks + heavy background processes running = new epileptic is born

### ISSUE THREAD

**Issue by ejnshtein** [cenk1cenk2/listr2#442] opened 2021-07-20 13:06 UTC
Hi guys!

This library is very cool, we're using it in our [CMA project](https://github.com/scandipwa/create-magento-app) to set up and run Magento 2 projects in a single command.

But I want to report, that we have "flashing" problems in a console when our program is running.
This problem appears everywhere: in VSCode, PHPStorm, ITerm2, Konsole and so on.

https://user-images.githubusercontent.com/18352350/126329085-bf8e9d6d-0882-4356-953f-4820e3a91004.mp4

It appears mostly when something heavy is running in the background, like PHP compilation or Magento setup, but can also flash it when the program is starting.

What do you think, where should I dig in to fix this problem?

Thanks in advance!

**Comment by cenk1cenk2** [comment] 2021-07-21 14:11
Hello @ejnshtein,

Thank you for the kind words. This is unfortunately pretty normal because it tries to update the renderer every 100ms or whenever a task changes state or gives output etc. This flickering can occur where it does not get enough CPU time and a task updates too frequently.

The solution to this will be to swap out the underlying library of `log-update` for `stdout-update`, which I have tried and can achieve to keep the lines that will not encounter any changes static and update only the rest minimizes this issue. But still has many problems with the compatibility of the tests. It also has a really old v4.0.0-beta version of this library to test it out.

I really do not know when I will really finish and merge it, but it's in my plans and since I want to archive more structural changes with the upcoming major update, currently I do not have the time for it. 

Listed in upcoming changes for a while now:
https://listr2.kilic.dev/migration/upcoming-changes

The related issue is tracked here:
https://github.com/cenk1cenk2/listr2/issues/296

**Comment by ejnshtein** [comment] 2021-07-21 14:23
That's good to hear!
We will try the beta version as well.

Thanks for your work!

**Comment by ejnshtein** [comment] 2021-07-21 14:27
Indeed, beta is not flickering, but it doesn't update properly the console. At least something is working :smile: 

![Screenshot_20210721_172542](https://user-images.githubusercontent.com/18352350/126505385-62e3c879-39ad-40c6-8efe-c931d06103fc.png)

Okay, will be waiting for the new major version! Good luck!

**Comment by cenk1cenk2** [comment] 2021-07-22 18:40
I will be closing this issue in favor of #296 . Feel free to reopen it any time. But the problem is acknowledged.

**Closed by cenk1cenk2** 2021-07-22 18:40 UTC

**Comment by cdwmhcc** [comment] 2023-11-30 21:25
``` ts
import { execaCommand as command } from 'execa'
import { Listr } from 'listr2'

const tasks = new Listr([
  {
    title: 'This task will do a curl request.',
    task: async (_, task): Promise<void> => {
      const execute = command('rsync -a --info=progress2 /path/to/[big folder] /path/to/dest')

      execute.stdout.pipe(task.stdout())
      execute.stderr.pipe(task.stdout())

      await execute
    },
    rendererOptions: {
      outputBar: Infinity,
      persistentOutput: true
    }
  }
])

await tasks.run()
```

Just a simple test:

It flashes on macOS 14.0 (23A344)
