### ISSUE TITLE
Pause output in the renderer

### ISSUE THREAD

**Issue by EvanPurkhiser** [cenk1cenk2/listr2#450] opened 2021-07-28 05:38 UTC
I have a use case where I would like to start some tasks, but would like to immediately pause any output to the terminal. Specifically because while the tasks are executing, I would like to open the users `$EDITOR` with `spawn`, which means I need the executed editor process to control stdout.

Without pausing the listr output, I the editor interface becomes corrupted.

What I would prefer is if I was able to pause and unpause the output, while still allowing the tasks to run in the background.

Alternatively if there was a way to swap renderers while tasks are executing that would be nice as well.

**Comment by cenk1cenk2** [comment] 2021-07-28 10:54
Hello @EvanPurkhiser ,

I guess this is not easily possible, neither swapping the renderers on runtime nor pausing the execution and unhooking stdout.

But for an editor, only you can try the same approach I use which successfully launches the default editor of the user.

Example can be found here:
https://github.com/cenk1cenk2/cz-cc/blob/3905765112ae70c2d4e08190bbab2eb938f87771/src/engine.js#L139

**Comment by cenk1cenk2** [comment] 2021-08-31 14:38
I will close this since, I have no plan to implement it by myself, with the plans that changing the render output fully to some other library. If a pull request comes after that, I will happily integrate that function. But the problem is this is not easily implementable.

**Closed by cenk1cenk2** 2021-08-31 14:38 UTC
