### ISSUE TITLE
Task status symbols abruptly cut-off

### ISSUE THREAD

**Issue by a2chan** [cenk1cenk2/listr2#30] opened 2020-05-20 11:00 UTC
![image](https://user-images.githubusercontent.com/46082775/82438632-fac28980-9ab6-11ea-8971-a62274e782cb.png)

Font: Ubuntu Mono
Terminal: zsh
ZSH theme: Spaceship

They work perfectly well with DejaVu Sans Mono but not with any other Mono fonts.

**Comment by cenk1cenk2** [comment] 2020-05-20 14:18
Hmm that might be due to the charachter width limitation. I do not know how to fix that, since it is using an external library to provide the symbols. But I will take a look in the longer run.

**Comment by a2chan** [comment] 2020-05-20 18:01
Yes, v10.2.4.

**Comment by cenk1cenk2** [comment] 2020-05-25 19:44
I am going to close this for now, if it is okay with you. But it will be back of my mind even though I think this might be caused by the terminal character width.

**Closed by cenk1cenk2** 2020-05-25 19:44 UTC
