### ISSUE TITLE
Strange behavior with many tasks

### ISSUE THREAD

**Issue by pbelbin** [cenk1cenk2/listr2#438] opened 2021-06-21 23:17 UTC
When I have a Listr2 instance that is loaded up with a large-ish number of tasks, the output behavior is quite variable.

In the case where there's a reasonably deep terminal window, it has a phase of behavior where it 'eats' the oldest lines of text.

[see here](https://user-images.githubusercontent.com/10079005/122838975-c3776b00-d2bc-11eb-9eff-831feb879cb9.mp4)

On the other hand, if the available number of rows is smaller, it might just blank the output entirely until the very end:

[see here - wait till the end - it does re-appear](https://user-images.githubusercontent.com/10079005/122839017-d68a3b00-d2bc-11eb-9d12-755d8f576f58.mp4)

In order to see this behavior, take a look at the video, you'll see where I've added the following lines to the `demo.example.ts` at line 186.

Here is what I added:

```ts
                ...(new Array(300).fill(undefined).map((v, i) => {
                  return {
                    title: `Title ${i} ipsum lorem stunum julius cesar julie ides of march rinse the blood off my toga`,
                    task: async (): Promise<void> => {
                      await delay(20000 * Math.random());
                    }
                  }
                })),
```

**Comment by cenk1cenk2** [comment] 2021-06-23 15:46
Hello @pbelbin ,

Thank you for this issue. This has been discussed [here](https://github.com/cenk1cenk2/listr2/issues/296). This is mostly a problem of how we can handle the terminal and have no proper access to the lines that are not inside the seen window. So this deleting behavior of the lines is somewhat related to the underlying library `log-update`.

I plan to swap it out but still could not get it to work properly with the tests. The things I want to do before releasing a major version is listed in [upcoming changes](https://listr2.kilic.dev/migration/upcoming-changes). So it will be a bit of time still this hits mainstream.

**Comment by cenk1cenk2** [comment] 2021-07-22 18:40
I will be closing this issue in favor of #296 . Feel free to reopen it any time. But the problem is acknowledged.

**Closed by cenk1cenk2** 2021-07-22 18:40 UTC
